// main.go
package main

import (
	"context"
	"errors"
	"flag"
	"fmt"
	"log/slog"
	"net"
	"os"
	"os/signal"
	"syscall"

	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/link"
)

// The directive below instructs `go generate` to run the Cilium `bpf2go` generator tool.
// It compiles xdp.c with Clang into eBPF bytecode targeting both little-endian (bpfel)
// and big-endian (bpfeb) architectures, producing Go scaffolding:
//   - fastpathObjects (holding XdpPolicy program and BlockedPort map)
//   - loadFastpathObjects (loads and verifies the bytecode in the Linux kernel)
//
// To generate bindings prior to building on a Linux machine with clang installed, run:
//   go generate ./...
//
//go:generate go run github.com/cilium/ebpf/cmd/bpf2go -target bpfel,bpfeb fastpath xdp.c

/*
run orchestrates the lifecycle of the eBPF FastPath filter:
 1. Resolves the Linux network interface by name.
 2. Loads and verifies the compiled eBPF objects (programs and maps) into the kernel.
 3. Writes the desired UDP destination port into the BPF array map (kernel-userspace IPC).
 4. Attaches the XDP program directly to the network interface driver ring.
 5. Blocks until context cancellation (SIGINT/SIGTERM), cleanly detaching upon exit.
*/
func run(ctx context.Context, name string, port uint) error {
	// UDP ports are 16-bit integers (0 to 65535). Validate before proceeding.
	if port > 65535 {
		return fmt.Errorf("port out of range: %d", port)
	}

	// 1. Resolve network interface
	// net.InterfaceByName queries the OS to find the interface and retrieve its Index (ifindex).
	// XDP links bind to this numeric index via Netlink.
	iface, err := net.InterfaceByName(name)
	if err != nil {
		return fmt.Errorf("interface %q: %w", name, err)
	}

	// 2. Load eBPF Objects into the Kernel
	// fastpathObjects and loadFastpathObjects are generated by bpf2go from xdp.c.
	// When loadFastpathObjects executes:
	//   - The eBPF bytecode is submitted to the kernel via the bpf() system call.
	//   - The kernel eBPF verifier verifies static safety (no unbounded loops, valid bounds).
	//   - Maps and programs are allocated kernel memory and return file descriptors.
	var objs fastpathObjects

	if err := loadFastpathObjects(&objs, nil); err != nil {
		// If verification fails, the kernel returns a detailed verifier log explaining
		// which instruction violated memory safety or type constraints.
		return fmt.Errorf("load eBPF (inspect verifier log): %w", err)
	}
	defer objs.Close() // Releases map and program file descriptors on return

	// 3. Configure Policy via eBPF Map (Kernel-Userspace Shared State)
	// The map 'blocked_port' in xdp.c is an ARRAY of size 1 (key type __u32, value __u16).
	// We update index 0 with our target UDP destination port.
	// Any incoming UDP packet with this destination port will be dropped (XDP_DROP).
	// If port is 0, xdp.c treats it as disabled and passes all packets (XDP_PASS).
	key := uint32(0)
	value := uint16(port)

	// ebpf.UpdateAny allows creating or updating the entry.
	if err := objs.BlockedPort.Update(key, value, ebpf.UpdateAny); err != nil {
		return fmt.Errorf("set blocked port: %w", err)
	}

	// 4. Attach Program to XDP Hook Point
	// link.AttachXDP attaches the program to the network driver's RX path.
	// By default, this uses the driver's native XDP mode if supported, or falls back to
	// generic XDP. In native mode, packets are evaluated and dropped at wire speed
	// before any socket buffer (sk_buff) allocation occurs in the Linux TCP/IP stack.
	attached, err := link.AttachXDP(link.XDPOptions{
		Program:   objs.XdpPolicy,
		Interface: iface.Index,
	})
	if err != nil {
		return fmt.Errorf("attach XDP on %q: %w", name, err)
	}
	// Ensuring attached.Close() is deferred detaches the XDP hook from the NIC
	// when the application shuts down, preventing interfaces from remaining blocked.
	defer attached.Close()

	slog.Info(
		"XDP active",
		"interface", name,
		"blocked_udp_port", port,
	)

	// Block until signal handler cancels the context (e.g. Ctrl+C or SIGTERM)
	<-ctx.Done()

	return nil
}

func main() {
	// Command-line flag parsing
	name := flag.String(
		"iface",
		"",
		"ingress interface (e.g., eth0, veth0)",
	)

	port := flag.Uint(
		"port",
		0,
		"UDP destination port to block (1-65535); 0 means pass all traffic",
	)

	flag.Parse()

	// Ensure interface name is provided
	if *name == "" {
		fmt.Fprintln(os.Stderr, "-iface is required")
		os.Exit(2)
	}

	// Graceful shutdown handling:
	// Registers SIGINT (Ctrl+C) and SIGTERM handlers.
	// When caught, ctx.Done() closes, triggering clean unhooking of the XDP link.
	ctx, stop := signal.NotifyContext(
		context.Background(),
		os.Interrupt,
		syscall.SIGTERM,
	)
	defer stop()

	if err := run(ctx, *name, *port); err != nil &&
		!errors.Is(err, context.Canceled) {

		slog.Error("agent stopped", "error", err)
		os.Exit(1)
	}
}
